export const FIELD_TYPE = {
  COLOR: 'color',
  DATE: 'date',
  DATE_TIME_LOCAL: 'datetime-local',
  EMAIL: 'email',
  FILE: 'file',
  HIDDEN: 'hidden',
  MONTH: 'month',
  NUMBER: 'number',
  PASSWORD: 'password',
  RANGE: 'range',
  TEL: 'tel',
  TEXT: 'text',
  TEXTAREA: 'textarea',
  TIME: 'time',
  URL: 'url',
  RADIO: 'radio',
  RESET: 'reset',
  SEARCH: 'search',
  SELECT: 'select',
  SUBMIT: 'submit',
  WEEK: 'week',
};
